conditioning:
  method: ps
  params:
    scale: 0.7

data:
  name: hsi
  root: ./data/hsi/cave
  image_size: 256

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    mask_prob_range: !!python/tuple [0.3, 0.7]
  noise:
    name: gaussian
    sigma: 0.05
