conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: hsi
  root: ./data/hsi/cave
  image_size: 256

measurement:
  operator:
    name: super_resolution
    in_shape: [31, 256, 256]
    scale_factor: 4
  noise:
    name: gaussian
    sigma: 0.02
